/**
 * Sistema de Permissões e Roles
 * Define hierarquia e permissões por perfil
 */

// Perfis disponíveis no sistema
export const ROLES = {
  // Super Admin - Controle total do SaaS
  SUPER_ADMIN: 'super_admin',
  
  // Administrador do Escritório - Controle total do tenant
  ADMIN_ESCRITORIO: 'admin_escritorio',
  
  // Sócio - Acesso completo aos dados do escritório
  SOCIO: 'socio',
  
  // Coordenador Jurídico - Gerencia equipe e processos
  COORDENADOR: 'coordenador',
  
  // Advogado - Acesso aos seus processos
  ADVOGADO: 'advogado',
  
  // Advogado Associado - Acesso limitado
  ADVOGADO_ASSOCIADO: 'advogado_associado',
  
  // Estagiário - Acesso somente leitura
  ESTAGIARIO: 'estagiario',
  
  // Assistente Jurídico - Suporte administrativo
  ASSISTENTE: 'assistente',
  
  // Financeiro - Acesso ao módulo financeiro
  FINANCEIRO: 'financeiro',
  
  // Recepção/Secretaria - Acesso básico
  RECEPCAO: 'recepcao',
  
  // Correspondente - Acesso externo limitado
  CORRESPONDENTE: 'correspondente',
  
  // Cliente - Portal do cliente
  CLIENTE: 'cliente',
}

// Hierarquia de roles (quem pode gerenciar quem)
export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: [ROLES.ADMIN_ESCRITORIO],
  [ROLES.ADMIN_ESCRITORIO]: [ROLES.SOCIO, ROLES.COORDENADOR, ROLES.ADVOGADO, ROLES.FINANCEIRO, ROLES.RECEPCAO],
  [ROLES.SOCIO]: [ROLES.COORDENADOR, ROLES.ADVOGADO, ROLES.ADVOGADO_ASSOCIADO, ROLES.ESTAGIARIO, ROLES.ASSISTENTE],
  [ROLES.COORDENADOR]: [ROLES.ADVOGADO, ROLES.ADVOGADO_ASSOCIADO, ROLES.ESTAGIARIO, ROLES.ASSISTENTE],
  [ROLES.ADVOGADO]: [ROLES.ESTAGIARIO, ROLES.ASSISTENTE],
}

// Permissões por módulo
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',
  DASHBOARD_ADMIN: 'dashboard:admin',
  
  // Processos
  PROCESSOS_VIEW: 'processos:view',
  PROCESSOS_CREATE: 'processos:create',
  PROCESSOS_EDIT: 'processos:edit',
  PROCESSOS_DELETE: 'processos:delete',
  PROCESSOS_ADMIN: 'processos:admin', // Ver todos os processos
  
  // Clientes
  CLIENTES_VIEW: 'clientes:view',
  CLIENTES_CREATE: 'clientes:create',
  CLIENTES_EDIT: 'clientes:edit',
  CLIENTES_DELETE: 'clientes:delete',
  
  // Agenda
  AGENDA_VIEW: 'agenda:view',
  AGENDA_CREATE: 'agenda:create',
  AGENDA_EDIT: 'agenda:edit',
  AGENDA_DELETE: 'agenda:delete',
  AGENDA_ADMIN: 'agenda:admin', // Ver agenda de outros
  
  // Documentos
  DOCUMENTOS_VIEW: 'documentos:view',
  DOCUMENTOS_CREATE: 'documentos:create',
  DOCUMENTOS_EDIT: 'documentos:edit',
  DOCUMENTOS_DELETE: 'documentos:delete',
  DOCUMENTOS_SIGN: 'documentos:sign',
  
  // Financeiro
  FINANCEIRO_VIEW: 'financeiro:view',
  FINANCEIRO_CREATE: 'financeiro:create',
  FINANCEIRO_EDIT: 'financeiro:edit',
  FINANCEIRO_DELETE: 'financeiro:delete',
  FINANCEIRO_ADMIN: 'financeiro:admin',
  FINANCEIRO_REPORTS: 'financeiro:reports',
  
  // Usuários
  USUARIOS_VIEW: 'usuarios:view',
  USUARIOS_CREATE: 'usuarios:create',
  USUARIOS_EDIT: 'usuarios:edit',
  USUARIOS_DELETE: 'usuarios:delete',
  USUARIOS_PERMISSIONS: 'usuarios:permissions',
  
  // Configurações
  CONFIG_VIEW: 'config:view',
  CONFIG_EDIT: 'config:edit',
  
  // Relatórios
  RELATORIOS_VIEW: 'relatorios:view',
  RELATORIOS_CREATE: 'relatorios:create',
  
  // IA
  IA_USE: 'ia:use',
  IA_ADMIN: 'ia:admin',
  
  // Tribunais
  TRIBUNAIS_CONSULT: 'tribunais:consult',
  TRIBUNAIS_ADMIN: 'tribunais:admin',
  
  // Auditoria
  AUDIT_VIEW: 'audit:view',
}

// Permissões por role
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.ADMIN_ESCRITORIO]: [
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_CREATE, PERMISSIONS.PROCESSOS_EDIT, PERMISSIONS.PROCESSOS_DELETE, PERMISSIONS.PROCESSOS_ADMIN,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE, PERMISSIONS.CLIENTES_EDIT, PERMISSIONS.CLIENTES_DELETE,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT, PERMISSIONS.AGENDA_DELETE, PERMISSIONS.AGENDA_ADMIN,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE, PERMISSIONS.DOCUMENTOS_EDIT, PERMISSIONS.DOCUMENTOS_DELETE, PERMISSIONS.DOCUMENTOS_SIGN,
    PERMISSIONS.FINANCEIRO_VIEW, PERMISSIONS.FINANCEIRO_CREATE, PERMISSIONS.FINANCEIRO_EDIT, PERMISSIONS.FINANCEIRO_DELETE, PERMISSIONS.FINANCEIRO_ADMIN, PERMISSIONS.FINANCEIRO_REPORTS,
    PERMISSIONS.USUARIOS_VIEW, PERMISSIONS.USUARIOS_CREATE, PERMISSIONS.USUARIOS_EDIT, PERMISSIONS.USUARIOS_DELETE, PERMISSIONS.USUARIOS_PERMISSIONS,
    PERMISSIONS.CONFIG_VIEW, PERMISSIONS.CONFIG_EDIT,
    PERMISSIONS.RELATORIOS_VIEW, PERMISSIONS.RELATORIOS_CREATE,
    PERMISSIONS.IA_USE, PERMISSIONS.IA_ADMIN,
    PERMISSIONS.TRIBUNAIS_CONSULT, PERMISSIONS.TRIBUNAIS_ADMIN,
    PERMISSIONS.AUDIT_VIEW,
  ],
  
  [ROLES.SOCIO]: [
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_CREATE, PERMISSIONS.PROCESSOS_EDIT, PERMISSIONS.PROCESSOS_ADMIN,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE, PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT, PERMISSIONS.AGENDA_DELETE, PERMISSIONS.AGENDA_ADMIN,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE, PERMISSIONS.DOCUMENTOS_EDIT, PERMISSIONS.DOCUMENTOS_SIGN,
    PERMISSIONS.FINANCEIRO_VIEW, PERMISSIONS.FINANCEIRO_CREATE, PERMISSIONS.FINANCEIRO_EDIT, PERMISSIONS.FINANCEIRO_REPORTS,
    PERMISSIONS.USUARIOS_VIEW, PERMISSIONS.USUARIOS_CREATE, PERMISSIONS.USUARIOS_EDIT,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.RELATORIOS_VIEW, PERMISSIONS.RELATORIOS_CREATE,
    PERMISSIONS.IA_USE,
    PERMISSIONS.TRIBUNAIS_CONSULT,
  ],
  
  [ROLES.COORDENADOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_CREATE, PERMISSIONS.PROCESSOS_EDIT, PERMISSIONS.PROCESSOS_ADMIN,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE, PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT, PERMISSIONS.AGENDA_DELETE, PERMISSIONS.AGENDA_ADMIN,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE, PERMISSIONS.DOCUMENTOS_EDIT, PERMISSIONS.DOCUMENTOS_SIGN,
    PERMISSIONS.FINANCEIRO_VIEW,
    PERMISSIONS.USUARIOS_VIEW, PERMISSIONS.USUARIOS_CREATE, PERMISSIONS.USUARIOS_EDIT,
    PERMISSIONS.RELATORIOS_VIEW,
    PERMISSIONS.IA_USE,
    PERMISSIONS.TRIBUNAIS_CONSULT,
  ],
  
  [ROLES.ADVOGADO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_CREATE, PERMISSIONS.PROCESSOS_EDIT,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE, PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT, PERMISSIONS.AGENDA_DELETE,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE, PERMISSIONS.DOCUMENTOS_EDIT, PERMISSIONS.DOCUMENTOS_SIGN,
    PERMISSIONS.FINANCEIRO_VIEW,
    PERMISSIONS.RELATORIOS_VIEW,
    PERMISSIONS.IA_USE,
    PERMISSIONS.TRIBUNAIS_CONSULT,
  ],
  
  [ROLES.ADVOGADO_ASSOCIADO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_CREATE, PERMISSIONS.PROCESSOS_EDIT,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE, PERMISSIONS.DOCUMENTOS_EDIT,
    PERMISSIONS.IA_USE,
  ],
  
  [ROLES.ESTAGIARIO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.AGENDA_VIEW,
    PERMISSIONS.DOCUMENTOS_VIEW,
  ],
  
  [ROLES.ASSISTENTE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW, PERMISSIONS.PROCESSOS_EDIT,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT,
    PERMISSIONS.DOCUMENTOS_VIEW, PERMISSIONS.DOCUMENTOS_CREATE,
  ],
  
  [ROLES.FINANCEIRO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.FINANCEIRO_VIEW, PERMISSIONS.FINANCEIRO_CREATE, PERMISSIONS.FINANCEIRO_EDIT, PERMISSIONS.FINANCEIRO_DELETE, PERMISSIONS.FINANCEIRO_REPORTS,
    PERMISSIONS.RELATORIOS_VIEW,
  ],
  
  [ROLES.RECEPCAO]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW,
    PERMISSIONS.CLIENTES_VIEW, PERMISSIONS.CLIENTES_CREATE, PERMISSIONS.CLIENTES_EDIT,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE, PERMISSIONS.AGENDA_EDIT,
  ],
  
  [ROLES.CORRESPONDENTE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROCESSOS_VIEW,
    PERMISSIONS.AGENDA_VIEW, PERMISSIONS.AGENDA_CREATE,
    PERMISSIONS.DOCUMENTOS_VIEW,
  ],
  
  [ROLES.CLIENTE]: [
    PERMISSIONS.PROCESSOS_VIEW,
    PERMISSIONS.DOCUMENTOS_VIEW,
  ],
}

/**
 * Verifica se um usuário tem uma permissão específica
 */
export function hasPermission(userRole, permission, customPermissions = null) {
  // Super admin tem todas as permissões
  if (userRole === ROLES.SUPER_ADMIN) return true
  
  // Verifica permissões customizadas primeiro
  if (customPermissions) {
    if (customPermissions.includes(permission) || customPermissions.includes('*')) {
      return true
    }
  }
  
  // Verifica permissões do role
  const rolePerms = ROLE_PERMISSIONS[userRole] || []
  return rolePerms.includes(permission)
}

/**
 * Verifica se um usuário pode gerenciar outro
 */
export function canManage(managerRole, targetRole) {
  if (managerRole === ROLES.SUPER_ADMIN) return true
  if (managerRole === targetRole) return true
  
  const manageableRoles = ROLE_HIERARCHY[managerRole] || []
  return manageableRoles.includes(targetRole)
}

/**
 * Lista todos os roles disponíveis
 */
export function getAvailableRoles() {
  return Object.entries(ROLES).map(([key, value]) => ({
    key,
    value,
    label: getRoleLabel(value),
  }))
}

/**
 * Retorna label amigável para o role
 */
export function getRoleLabel(role) {
  const labels = {
    [ROLES.SUPER_ADMIN]: 'Super Administrador',
    [ROLES.ADMIN_ESCRITORIO]: 'Administrador do Escritório',
    [ROLES.SOCIO]: 'Sócio',
    [ROLES.COORDENADOR]: 'Coordenador Jurídico',
    [ROLES.ADVOGADO]: 'Advogado',
    [ROLES.ADVOGADO_ASSOCIADO]: 'Advogado Associado',
    [ROLES.ESTAGIARIO]: 'Estagiário',
    [ROLES.ASSISTENTE]: 'Assistente Jurídico',
    [ROLES.FINANCEIRO]: 'Financeiro',
    [ROLES.RECEPCAO]: 'Recepção/Secretaria',
    [ROLES.CORRESPONDENTE]: 'Correspondente',
    [ROLES.CLIENTE]: 'Cliente',
  }
  
  return labels[role] || role
}
